export enum Can {
  START = "START",
  CREATE_TURN = "CREATE_TURN",
  WHO_TURN = "WHO_TURN",
  SEND_DICE = "SEND_DICE",
  CHOOSE_MOVE = "CHOOSE_MOVE",
  MOVE = "MOVE",
  END_MOVE = "END_MOVE",
  END_TURN = "END_TURN",
}
