export enum Can {
  START_GAME = "START_GAME",
  START_TURN = "START_TURN",
  WHO_TURN = "WHO_TURN",
  SEND_DICE = "SEND_DICE",
  CHOOSE_MOVE = "CHOOSE_MOVE",
  MOVE = "MOVE",
  END_MOVE = "END_MOVE",
  END_TURN = "END_TURN",
}

